language: objective-c
osx_image: xcode11.3
os: osx

cache: 
  cocoapods: true
  directories:
    - /home/travis/.rvm/

env:
    global:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
  
before_install:
  - sudo gem install xcpretty

before_script:
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace './YAHTTPVCR.xcworkspace' -scheme '[Test] iOS Code Coverage (Full)' -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.4' build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=YES | xcpretty --simple

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
